### PR TITLE
added viewbox

### PR DESCRIPTION
**Pull request by nico-martin**
Clean solution instead of #202

### CODE REVIEW

**Comment by nico-martin** [comment]
After seeing where @rosskhanas lives I assume that right now he has a completely different focus than a few pull requests. As long as this PR is open, I have published a new package on NPM. Feel free to use it, but I will use the orginal package again later (so I won't maintain it further): https://www.npmjs.com/package/@nico-martin/react-qr-code

**Comment by rosskhanas** [comment]
> After seeing where @rosskhanas lives I assume that right now he has a completely different focus than a few pull requests. As long as this PR is open, I have published a new package on NPM. Feel free to use it, but I will use the orginal package again later (so I won't maintain it further): https://www.npmjs.com/package/@nico-martin/react-qr-code

Hey Nico, I'm safe here, in Lviv. Thank you for understanding and for your PR too. I will do my best to check both PRs this weekend 🥲

**Comment by nico-martin** [comment]
> > After seeing where @rosskhanas lives I assume that right now he has a completely different focus than a few pull requests. As long as this PR is open, I have published a new package on NPM. Feel free to use it, but I will use the orginal package again later (so I won't maintain it further): https://www.npmjs.com/package/@nico-martin/react-qr-code
> 
> Hey Nico, I'm safe here, in Lviv. Thank you for understanding and for your PR too. I will do my best to check both PRs this weekend 🥲

That's great to hear. Again, it is not urgent at all. Just take a look when you have time.

**Comment by rosskhanas** [comment]
I always wanted to keep this lib a bit minimal, therefore I'm not sure it is good to introduce new parameters. Especially considering that the needed result can be achieved now. 

Here is a commit with a code and a demo: https://github.com/rosskhanas/react-qr-code/commit/1f43adb3b41305b9a3ab004b337b3bd34bf9fe6c

https://rosskhanas.github.io/react-qr-code/

@nico-martin what is your opinion? 😃

**Comment by nico-martin** [comment]
Ah I see. Sure, that could be a workaround. I personally like the `useViewBox` prop. Bt as long there is a workaround, I'm fine 👍

**Pull request closed without merging**
