### PR TITLE
Remove missing prop from readme

### PR DESCRIPTION
**Pull request by rickythefox**
Ridiculous PR, but here goes.... The `title` prop does not exist.

### CODE REVIEW

**Comment by Joe-Alfaro** [comment]
It looks like the title prop does not exist in the propTypes but QrCodeSvg can make use of the title prop. I think instead of removing title from the readme you should add it to the propType in index.js, and implement it in QrCodeSvg/index.native.js same as in QrCodeSvg/index.js

**Comment by rosskhanas** [comment]
That is not 100% true. It does exist on web. Unfortunately `react-native-svg` does not support title tag https://github.com/software-mansion/react-native-svg/issues/1404

**Comment by Joe-Alfaro** [comment]
Oh thanks, I didn't know that about React Native. What would be the right way forward then in regards to the parent component's propTypes? It seems like if added then it could be confusing on React Native why the title isn't being added

**Comment by rosskhanas** [comment]
I just added a platform column to the README.md https://github.com/rosskhanas/react-qr-code/tree/master?tab=readme-ov-file#api

**Pull request closed without merging**
